# Generated by Django 4.1.3 on 2022-12-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=225)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('guest_number', models.IntegerField()),
                ('checkIns', models.CharField(max_length=10)),
                ('checkOut', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=225)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('guest_number', models.IntegerField()),
                ('checkIns', models.CharField(max_length=10)),
                ('checkOut', models.CharField(max_length=10)),
            ],
        ),
    ]
